sudo: required
services: 
  - docker

before_install:
  - docker build -t shreekarhegde/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shreekarhegde/react-test npm test -- --coverage

after_success:
  - docker build -t shreekarhegde/multi-client ./client
  - docker build -t shreekarhegde/multi-nginx ./nginx
  - docker build -t shreekarhegde/multi-server ./server  
  - docker build -t shreekarhegde/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shreekarhegde/multi-client
  - docker push shreekarhegde/multi-nginx
  - docker push shreekarhegde/multi-server
  - docker push shreekarhegde/multi-worker